FROM labtainers/labtainer.base2:latest
ARG lab
ARG labdir
ARG imagedir
ENV HOME /home/ubuntu
RUN useradd -m -s /bin/bash ubuntu || true
WORKDIR /home/ubuntu
ADD $labdir/$lab.tar.gz /home/ubuntu
RUN chown -R ubuntu:ubuntu /home/ubuntu && chmod +x /home/ubuntu/stego/*.py
